[2025-03-26T06:43:48.050+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-26T06:43:48.055+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: import_user_session_data_from_s3.copy_user_session_channel scheduled__2025-03-25T00:00:00+00:00 [queued]>
[2025-03-26T06:43:48.057+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: import_user_session_data_from_s3.copy_user_session_channel scheduled__2025-03-25T00:00:00+00:00 [queued]>
[2025-03-26T06:43:48.058+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-03-26T06:43:48.061+0000] {taskinstance.py:2888} INFO - Executing <Task(SnowflakeOperator): copy_user_session_channel> on 2025-03-25 00:00:00+00:00
[2025-03-26T06:43:48.064+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=278) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-26T06:43:48.064+0000] {standard_task_runner.py:72} INFO - Started process 281 to run task
[2025-03-26T06:43:48.064+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'import_user_session_data_from_s3', 'copy_user_session_channel', 'scheduled__2025-03-25T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/import_user_session_data.py', '--cfg-path', '/tmp/tmp87z926_o']
[2025-03-26T06:43:48.065+0000] {standard_task_runner.py:105} INFO - Job 10: Subtask copy_user_session_channel
[2025-03-26T06:43:48.079+0000] {task_command.py:467} INFO - Running <TaskInstance: import_user_session_data_from_s3.copy_user_session_channel scheduled__2025-03-25T00:00:00+00:00 [running]> on host 2bee9cd353de
[2025-03-26T06:43:48.101+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='import_user_session_data_from_s3' AIRFLOW_CTX_TASK_ID='copy_user_session_channel' AIRFLOW_CTX_EXECUTION_DATE='2025-03-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-25T00:00:00+00:00'
[2025-03-26T06:43:48.101+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-26T06:43:48.107+0000] {sql.py:266} INFO - Executing: 
    COPY INTO dev.raw.user_session_channel
    FROM @dev.raw.blob_stage/user_session_channel.csv;
    
[2025-03-26T06:43:48.110+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-03-26T06:43:48.112+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-03-26T06:43:48.112+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.12.5-linuxkit-aarch64-with-glibc2.36
[2025-03-26T06:43:48.113+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-26T06:43:48.113+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-26T06:43:48.608+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-03-26T06:43:48.608+0000] {sql.py:509} INFO - Running statement: COPY INTO dev.raw.user_session_channel
    FROM @dev.raw.blob_stage/user_session_channel.csv;, parameters: None
[2025-03-26T06:43:48.730+0000] {connection.py:788} INFO - closed
[2025-03-26T06:43:48.780+0000] {connection.py:794} INFO - No async queries seem to be running, deleting session
[2025-03-26T06:43:48.837+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 272, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 410, in run
    self._run_command(cur, sql_statement, parameters)  # type: ignore[attr-defined]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 1087, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 284, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 339, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 215, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 001757 (42601): 01bb42b3-0004-ccc2-0005-a9f70003208e: SQL compilation error:
Table 'DEV.RAW.USER_SESSION_CHANNEL' does not exist
[2025-03-26T06:43:48.851+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=import_user_session_data_from_s3, task_id=copy_user_session_channel, run_id=scheduled__2025-03-25T00:00:00+00:00, execution_date=20250325T000000, start_date=20250326T064348, end_date=20250326T064348
[2025-03-26T06:43:48.861+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-26T06:43:48.861+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 10 for task copy_user_session_channel (001757 (42601): 01bb42b3-0004-ccc2-0005-a9f70003208e: SQL compilation error:
Table 'DEV.RAW.USER_SESSION_CHANNEL' does not exist; 281)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 272, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 410, in run
    self._run_command(cur, sql_statement, parameters)  # type: ignore[attr-defined]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 1087, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 284, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 339, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 215, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 001757 (42601): 01bb42b3-0004-ccc2-0005-a9f70003208e: SQL compilation error:
Table 'DEV.RAW.USER_SESSION_CHANNEL' does not exist
[2025-03-26T06:43:48.895+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-26T06:43:48.904+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1378 AirflowProviderDeprecationWarning: Call to deprecated class SnowflakeOperator. (This class is deprecated. Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`. Also, you can provide `hook_params={'warehouse': <warehouse>, 'database': <database>, 'role': <role>, 'schema': <schema>, 'authenticator': <authenticator>,'session_parameters': <session_parameters>}`.)
[2025-03-26T06:43:48.911+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-26T06:43:48.914+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
